import { createShapeId, toRichText, type TLParentId } from '@tldraw/tlschema';
import { getIndicesBetween, type IndexKey } from '@tldraw/utils';
import type { TLShape } from 'tldraw';

/**
 * Curated starter canvases. Each template is a small hand-built tldraw
 * document (document-scope records only, the same format the room save path
 * persists) so a room can be created pre-populated. Seeding happens
 * client-side: buildTemplateSeed returns the canonical record map JSON, and
 * `createRoom({ seed })` stores it as the room's initial canvasData.
 *
 * The records are validated against tldraw's own schema in
 * `src/lib/templates.test.ts` so a malformed template fails the test suite
 * before it can ever reach a real room.
 */

export interface TemplateDef {
  id: string;
  name: string;
  tagline: string;
  category: 'architecture' | 'wireframe' | 'planning';
  /** Accent used by the template card, one of the app's neutral/green tokens. */
  accent: 'green' | 'ink';
}

export const TEMPLATES: TemplateDef[] = [
  {
    id: 'system-architecture',
    name: 'System architecture',
    tagline: 'Services, stores, and the arrows between them.',
    category: 'architecture',
    accent: 'green',
  },
  {
    id: 'signup-flow',
    name: 'Sign-up flow',
    tagline: 'A wireframe walkthrough from landing to dashboard.',
    category: 'wireframe',
    accent: 'ink',
  },
  {
    id: 'user-story-map',
    name: 'User story map',
    tagline: 'Activities and stories across a release spine.',
    category: 'planning',
    accent: 'ink',
  },
  {
    id: 'sprint-board',
    name: 'Sprint board',
    tagline: 'To do, doing, done — ready for your team.',
    category: 'planning',
    accent: 'green',
  },
];

export type TemplateId = (typeof TEMPLATES)[number]['id'];

const PAGE = 'page:page' as TLParentId;
const GRID = 20;

/** Valid, sortable order keys generated by tldraw's own fractional-indexing. */
const INDEX_KEYS = getIndicesBetween(null, null, 64);

function idx(n: number): IndexKey {
  return INDEX_KEYS[n];
}

interface GeoProps {
  x: number;
  y: number;
  w: number;
  h: number;
  label: string;
  color?: 'black' | 'green' | 'light-green';
  fill?: 'none' | 'semi';
  geo?: 'rectangle' | 'ellipse' | 'diamond' | 'cloud' | 'x-box';
  growY?: number;
}

function geo(tpl: string, n: number, p: GeoProps): TLShape {
  return {
    id: createShapeId(`${tpl}-${n}`),
    typeName: 'shape',
    type: 'geo',
    x: p.x,
    y: p.y,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    index: idx(n),
    parentId: PAGE,
    meta: {},
    props: {
      geo: p.geo ?? 'rectangle',
      dash: 'draw',
      url: '',
      w: p.w,
      h: p.h,
      growY: p.growY ?? 0,
      scale: 1,
      flipX: false,
      flipY: false,
      labelColor: 'black',
      color: p.color ?? 'black',
      fill: p.fill ?? 'none',
      size: 'm',
      font: 'draw',
      align: 'middle',
      verticalAlign: 'middle',
      richText: toRichText(p.label),
    },
  };
}

interface TextProps {
  x: number;
  y: number;
  w: number;
  text: string;
  color?: 'black' | 'green';
  size?: 's' | 'm';
}

function text(tpl: string, n: number, p: TextProps): TLShape {
  return {
    id: createShapeId(`${tpl}-${n}`),
    typeName: 'shape',
    type: 'text',
    x: p.x,
    y: p.y,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    index: idx(n),
    parentId: PAGE,
    meta: {},
    props: {
      color: p.color ?? 'black',
      size: p.size ?? 'm',
      font: 'draw',
      textAlign: 'start',
      w: p.w,
      richText: toRichText(p.text),
      scale: 1,
      autoSize: false,
    },
  };
}

interface NoteProps {
  x: number;
  y: number;
  w: number;
  text: string;
  color?: 'black' | 'green' | 'light-green' | 'blue' | 'yellow' | 'orange';
}

function note(tpl: string, n: number, p: NoteProps): TLShape {
  return {
    id: createShapeId(`${tpl}-${n}`),
    typeName: 'shape',
    type: 'note',
    x: p.x,
    y: p.y,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    index: idx(n),
    parentId: PAGE,
    meta: {},
    props: {
      color: p.color ?? 'yellow',
      labelColor: 'black',
      size: 'm',
      font: 'draw',
      fontSizeAdjustment: null,
      align: 'start',
      verticalAlign: 'start',
      growY: 0,
      url: '',
      richText: toRichText(p.text),
      scale: 1,
      textLastEditedBy: null,
    },
  };
}

interface ArrowProps {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  color?: 'black' | 'green';
  dash?: 'draw' | 'solid';
}

/** Unbound arrow: start/end are page-space points; the shape sits at origin. */
function arrow(tpl: string, n: number, p: ArrowProps): TLShape {
  return {
    id: createShapeId(`${tpl}-${n}`),
    typeName: 'shape',
    type: 'arrow',
    x: 0,
    y: 0,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    index: idx(n),
    parentId: PAGE,
    meta: {},
    props: {
      kind: 'arc',
      labelColor: 'black',
      color: p.color ?? 'black',
      fill: 'none',
      dash: p.dash ?? 'draw',
      size: 'm',
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      font: 'draw',
      start: { x: p.x1, y: p.y1 },
      end: { x: p.x2, y: p.y2 },
      bend: 0,
      richText: toRichText(''),
      labelPosition: 0.5,
      scale: 1,
      elbowMidPoint: 0,
    },
  };
}

function snap(v: number): number {
  return Math.round(v / GRID) * GRID;
}

/** System architecture: client → api → service, with db + cache downstream. */
function buildSystemArchitecture(): TLShape[] {
  const shapes: TLShape[] = [];
  let n = 0;

  const client = geo('arch', n++, { x: snap(0), y: snap(0), w: 200, h: 90, label: 'Client', color: 'green', fill: 'semi' });
  const api = geo('arch', n++, { x: snap(320), y: snap(0), w: 200, h: 90, label: 'API Gateway', color: 'black' });
  const service = geo('arch', n++, { x: snap(640), y: snap(0), w: 200, h: 90, label: 'Service', color: 'black' });
  const db = geo('arch', n++, { x: snap(640), y: snap(260), w: 200, h: 110, label: 'Database', color: 'black' });
  const cache = geo('arch', n++, { x: snap(320), y: snap(260), w: 200, h: 90, label: 'Cache', color: 'black', geo: 'ellipse' });
  shapes.push(client, api, service, db, cache);

  const cx = 200;
  shapes.push(
    arrow('arch', n++, { x1: snap(cx), y1: snap(45), x2: snap(320), y2: snap(45), color: 'green' }),
    arrow('arch', n++, { x1: snap(520), y1: snap(45), x2: snap(640), y2: snap(45), color: 'green' }),
    arrow('arch', n++, { x1: snap(740), y1: snap(90), x2: snap(740), y2: snap(260), color: 'black', dash: 'solid' }),
    arrow('arch', n++, { x1: snap(740), y1: snap(170), x2: snap(520), y2: snap(290), color: 'black', dash: 'solid' }),
    arrow('arch', n++, { x1: snap(520), y1: snap(305), x2: snap(420), y2: snap(305), color: 'black', dash: 'solid' }),
  );

  shapes.push(
    text('arch', n++, { x: snap(140), y: snap(140), w: 80, text: 'HTTPS', size: 's' }),
    text('arch', n++, { x: snap(460), y: snap(140), w: 80, text: 'RPC', size: 's' }),
    text('arch', n++, { x: snap(660), y: snap(200), w: 80, text: 'writes', size: 's' }),
    text('arch', n, { x: snap(500), y: snap(220), w: 80, text: 'reads', size: 's' }),
  );
  return shapes;
}

/** Sign-up flow: a wireframe walkthrough with arrows between frames. */
function buildSignupFlow(): TLShape[] {
  const shapes: TLShape[] = [];
  let n = 0;
  const W = 220;
  const H = 150;
  const GAP = 80;

  const frames = [
    { label: 'Landing', x: 0 },
    { label: 'Sign up', x: W + GAP },
    { label: 'Confirm email', x: (W + GAP) * 2 },
    { label: 'Dashboard', x: (W + GAP) * 3 },
  ];
  for (const f of frames) {
    shapes.push(
      geo('flow', n++, {
        x: snap(f.x),
        y: snap(0),
        w: W,
        h: H,
        label: f.label,
        color: f.label === 'Dashboard' ? 'green' : 'black',
        fill: f.label === 'Dashboard' ? 'semi' : 'none',
      })
    );
  }

  for (let i = 0; i < frames.length - 1; i++) {
    const from = frames[i].x + W;
    const to = frames[i + 1].x;
    shapes.push(arrow('flow', n++, { x1: snap(from), y1: snap(75), x2: snap(to), y2: snap(75), color: 'green' }));
  }

  const fieldY = H + 70;
  const fieldLabels = [
    { label: 'Email', x: frames[1].x + 20 },
    { label: 'Password', x: frames[1].x + 20, y: fieldY + 40 },
    { label: 'Code', x: frames[2].x + 20 },
  ];
  for (const f of fieldLabels) {
    shapes.push(
      text('flow', n++, { x: snap(f.x), y: snap(f.y ?? 0), w: 60, text: f.label, size: 's' }),
      geo('flow', n++, { x: snap(f.x), y: snap((f.y ?? 0) + 22), w: 180, h: 40, label: '', color: 'black', fill: 'none' })
    );
  }
  shapes.push(
    geo('flow', n++, { x: snap(frames[1].x + 20), y: snap(fieldY + 130), w: 180, h: 44, label: 'Continue', color: 'green', fill: 'semi' }),
    text('flow', n, { x: snap(frames[3].x + 20), y: snap(H + 70), w: 160, text: 'Welcome — open a template\nor start sketching.', size: 'm' })
  );
  return shapes;
}

/** User story map: spine activities + story cards below each. */
function buildUserStoryMap(): TLShape[] {
  const shapes: TLShape[] = [];
  let n = 0;
  const activities = [
    { label: 'Discover', x: 0 },
    { label: 'Sign up', x: 380 },
    { label: 'First sketch', x: 760 },
    { label: 'Collaborate', x: 1140 },
  ];
  const storyPool: string[][] = [
    ['See the product pitch', 'Understand the value'],
    ['Create account', 'Verify email'],
    ['Open a template', 'Draw a first shape'],
    ['Invite a teammate', 'Chat with the copilot'],
  ];
  for (const a of activities) {
    shapes.push(
      geo('story', n++, { x: snap(a.x), y: snap(0), w: 300, h: 70, label: a.label, color: 'green', fill: 'semi' })
    );
  }
  storyPool.forEach((stories, i) => {
    const baseY = 160;
    stories.forEach((s, j) => {
      shapes.push(
        note('story', n++, {
          x: snap(activities[i].x + j * 150),
          y: snap(baseY + (i % 2) * 130),
          w: 140,
          text: s,
          color: i % 2 === 0 ? 'yellow' : 'light-green',
        })
      );
    });
  });
  return shapes;
}

/** Sprint board: three columns of sticky notes under column headers. */
function buildSprintBoard(): TLShape[] {
  const shapes: TLShape[] = [];
  let n = 0;
  const columns = [
    { label: 'To do', x: 0, color: 'black' as const },
    { label: 'Doing', x: 360, color: 'black' as const },
    { label: 'Done', x: 720, color: 'black' as const },
  ];
  const colNotes = [
    ['Wire the copy button', 'Persist camera position', 'Empty-state illustration'],
    ['Smart float nudging', 'Template seeding'],
    ['Auth redesign', 'Glass surfaces'],
  ];
  columns.forEach((c, i) => {
    shapes.push(
      text('board', n++, { x: snap(c.x), y: snap(0), w: 200, text: c.label, size: 'm', color: i === 2 ? 'green' : 'black' })
    );
    colNotes[i].forEach((s, j) => {
      shapes.push(
        note('board', n++, { x: snap(c.x), y: snap(70 + j * 130), w: 220, text: s, color: i === 2 ? 'light-green' : 'yellow' })
      );
    });
  });
  return shapes;
}

const BUILDERS: Record<TemplateId, () => TLShape[]> = {
  'system-architecture': buildSystemArchitecture,
  'signup-flow': buildSignupFlow,
  'user-story-map': buildUserStoryMap,
  'sprint-board': buildSprintBoard,
};

export function buildTemplateSeed(templateId: string): string {
  const builder = BUILDERS[templateId as TemplateId];
  if (!builder) return '';
  const records: Record<string, TLShape> = {};
  for (const shape of builder()) {
    records[shape.id] = shape;
  }
  return JSON.stringify(records);
}
