import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  workspaces: defineTable({
    name: v.string(),
    ownerId: v.string(), // Clerk user ID
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_owner", ["ownerId"]),

  rooms: defineTable({
    workspaceId: v.id("workspaces"),
    name: v.string(),
    ownerId: v.string(), // Clerk user ID
    canvasData: v.optional(v.string()), // JSON canonical record map (document scope only)
    canvasVersion: v.number(), // monotonic, bumped by every change batch and snapshot
    // Optional for back-compat with rooms created before compaction existed; 0
    // means "no compaction yet" and canvasData is the exact snapshot at that version.
    compactedVersion: v.optional(v.number()),
    thumbnailData: v.optional(v.string()), // base64 PNG
    createdAt: v.number(),
    updatedAt: v.number(),
    // Last editor identity, written server-side by the canvas-change and rename
    // mutations. Never trusted from client input; display-only.
    lastEditedBy: v.optional(v.object({ id: v.string(), name: v.string() })),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_owner", ["ownerId"]),

  roomMembers: defineTable({
    roomId: v.id("rooms"),
    userId: v.string(), // Clerk user ID
    email: v.string(),
    name: v.optional(v.string()),
    avatarUrl: v.optional(v.string()),
    role: v.union(v.literal("owner"), v.literal("editor"), v.literal("viewer")),
    joinedAt: v.number(),
  })
    .index("by_room", ["roomId"])
    .index("by_user", ["userId"])
    .index("by_room_user", ["roomId", "userId"]),

  snapshots: defineTable({
    roomId: v.id("rooms"),
    version: v.number(),
    canvasData: v.string(), // JSON blob
    createdBy: v.string(), // Clerk user ID
    createdAt: v.number(),
    description: v.optional(v.string()),
    // Idempotency key: a full-state save retried after a dropped connection
    // must not create a duplicate history entry. Stability: generated by the
    // client before the mutation call and never reused.
    clientChangeId: v.optional(v.string()),
  })
    .index("by_room_version", ["roomId", "version"])
    .index("by_room", ["roomId"])
    .index("by_client_change", ["clientChangeId"]),

  aiMessages: defineTable({
    roomId: v.id("rooms"),
    userId: v.string(), // Clerk user ID (who asked)
    prompt: v.string(),
    response: v.string(),
    ghostBlocks: v.optional(v.string()), // JSON of suggested blocks
    status: v.union(v.literal("pending"), v.literal("completed"), v.literal("failed")),
    createdAt: v.number(),
  })
    .index("by_room", ["roomId"]),

  presence: defineTable({
    roomId: v.id("rooms"),
    userId: v.string(), // Clerk user ID
    name: v.string(),
    avatarUrl: v.optional(v.string()),
    color: v.string(),
    cursorX: v.optional(v.number()),
    cursorY: v.optional(v.number()),
    camera: v.optional(v.object({ x: v.number(), y: v.number(), zoom: v.number() })),
    selectedShapeIds: v.optional(v.array(v.string())),
    lastActive: v.number(),
  })
    .index("by_room", ["roomId"])
    .index("by_room_user", ["roomId", "userId"]),

  invites: defineTable({
    roomId: v.id("rooms"),
    email: v.string(),
    role: v.union(v.literal("editor"), v.literal("viewer")),
    invitedBy: v.string(), // Clerk user ID
    token: v.string(),
    status: v.union(v.literal("pending"), v.literal("accepted"), v.literal("expired")),
    createdAt: v.number(),
    expiresAt: v.number(),
  })
    .index("by_room", ["roomId"])
    .index("by_token", ["token"]),

  errorLogs: defineTable({
    userId: v.optional(v.string()), // Clerk user ID, if logged in
    source: v.string(), // e.g. "react", "api"
    message: v.string(),
    stack: v.optional(v.string()),
    componentStack: v.optional(v.string()),
    url: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_created", ["createdAt"]),
});
